export const graphs = [
    {
        id: 'revenue-by-month',
        name: 'Revenue by Month',
        vizState: {
            chartType: 'bar',
            query: {
                "measures": [
                    "Sales.total_revenue",
                ],
                "timeDimensions": [
                    {
                        "dimension": "Invoices.time",
                        "granularity": "month",
                    },
                ],
                "order": {}
            },
            pivotConfig: {
                "x": [
                  "Invoices.time.month"
                ],
                "y": [
                  "measures"
                ],
                "fillMissingDates": true,
                "joinDateRange": false,
            },
        },
    },
    {
        id: 'revenue-by-clothing-type',
        name: 'Revenue by Clothing Type',
        vizState: {
            chartType: 'pie',
            query: {
                "measures": [
                    "Sales.total_revenue",
                ],
                "order": {
                    "Sales.total_revenue": "desc",
                },
                "dimensions": [
                    "Barcodes.clothing_type_description",
                ],
            },
            pivotConfig: {
                "x": [
                    "Barcodes.clothing_type_description",
                ],
                "y": [
                    "measures",
                ],
                "fillMissingDates": true,
                "joinDateRange": false,
            },
        },
    },
    {
        id: 'inventory-by-clothing-type',
        name: 'Inventory by Clothing Type',
        vizState: {
            chartType: 'pie',
            query: {
                "measures": [
                    "Barcodes.total_quantity",
                ],
                "order": {
                    "Barcodes.total_quantity": "desc",
                },
                "dimensions": [
                    "Barcodes.clothing_type_description",
                ],
            },
            pivotConfig: {
                "x": [
                    "Barcodes.clothing_type_description",
                ],
                "y": [
                    "measures",
                ],
                "fillMissingDates": true,
                "joinDateRange": false,
            }
        },
    },
];

export const clothingTypes = [
    "BLUSA",
    "VESTIDO",
    "PANTALON",
    "FALDA",
    "SHORT",
    "JEAN",
    "ENTERIZO",
    "CONJUNTO",
    "SANDALIAS",
    "ZAPATOS",
    "PULSERA",
    "ARETE",
    "CHOKER",
    "FALDA SHORT",
    "SOMBRERO",
    "CAMISETA",
    "CORREA",
    "BUFANDAS",
    "CINTILLO",
    "ANILLO",
].sort();

export const silhouettes = [
    "LARGO",
    "CORTO",
    "MANGA CORTA",
    "CORTA",
    "LARGA",
    "MANGA LARGA",
    "CROP TOP",
    "ALTO",
    "ANUDADA",
    "PITILLO",
    "WRAP ROUND",
    "CHANEL",
    "KIMONO",
    "TUBO",
    "TIRAS",
    "BOTA TUBO",
    "COLA DE PATO",
    "CARNAVAL",
    "CULOTE",
    "AMPLIO",
    "CAMPESINA",
    "FALDA PANTALON",
    "MANGA SISA",
    "HALTER",
    "AMPLIA",
    "MANGA CAMPANA",
    "PLIZADA",
    "CROPTOP PANTALON",
    "MANGA 3/4",
    "PINZAS",
    "BODY",
    "ALTAS",
    "FALDA CROPTOP",
    "BOYFRIENDS",
    "PINZAS BOTA RECTA",
    "BLUSA FALDA",
    "POLLERA",
    "ARANDELAS",
    "CHANNEL",
    "MANGA GLOBO",
    "RUCHE",
    "RECTO",
    "RUCHE BOTA TUBO",
    "FALDA SHORT",
    "COLA PATO",
    "TALEGO",
    "UN HOMBRO  ",
    "CAMISERO",
    "CROPTOP FALDA",
    "BOTA AMPLIA CORTADA",
    "FALDA",
    "CROPTOP SHORT",
    "BOTA CAMPANA",
    "MANGA PLIZADA",
    "BLUSA PANTALON",
    "SHORT CROPTOP",
    "PLANAS",
    "AMARRADA CARNAVAL",
    "POLLERA ESPECIAL",
    "BOTA AMPLIA",
    "LARGA CARNAVAL",
    "TENIS",
    "COLA DE PATO CARNAVAL",
    "SHORT BLUSA",
    "ESTRAPLE",
    "METALICA",
    "BAJAS",
    "KIMONO SHORT",
    "ABIERTO",
    "PLIZADA LARGA",
    "CROPTOP FALDA SHORT",
    "TENNIS",
    "CAPRICE",
    "AJUS BOT ANGOST",
    "MANGA AMPLIA",
    "POLLERA 3 CAPAS",
    "BLUSA SHORT",
    "CROPTOP FALDA LARGA",
    "BOTA RECTA",
    "TACON MEDIANO",
    "MANGA GRANDE",
    "KIMONO CROPTOP CULOTTE",
    "PLANOS",
    "LARGA ARANDELAS",
    "CORSE",
    "CAMPESINO",
    "SHORT",
    "CROPTOP CULOTTE",
    "BAJOS",
    "CUELLO TORTUGA",
    "MARIPOSA ",
    "BOTA ARANDELAS",
    "CLASICO",
    "MIDLENGTH",
    " CROPTOP",
    "ALA GRANDE",
    "LARGO ABIERTO",
    "CORSET",
    "GARGANTILLA",
    "CUERO",
    "TIRAS CADENAS",
    "ALTOS",
    "STRAPLE ",
    "PEPLUM",
    "PLATAFORMA ALTAS",
    "ALTA",
    "CINTURILLA",
    "BANDEJA  ",
    "MANGA SISA ARANDELAS",
    "OVALADOS",
    "FLECOS",
    "REDONDOS PIEDRAS",
    "GRUESA",
    "PLASTICA TACON",
    "CASCADA",
    "PEQUEÑOS",
    "EXAGONAL",
    "ROMBOS",
    "LARGOS",
    "PIEDRAS",
    "DELGADA",
].sort();